### ISSUE TITLE
Fresh build error.

### ISSUE THREAD

**Issue by Acumen-Desktop** [codec-xyz/vtest#1]
I got this popup javascript error on first (and second) build:

```
Uncaught Exception:
TypeError: r.setTitleBarOverlay is not a function
at IpcMainImpl.<anonymous> (file:///Volumes/Data/Developer/Electron/2024-11-14/fap-core/.vite/build/main/main.js:70:19)
at IpcMainImpl.emit (node:events:519:28)
at WebContents.<anonymous> (node:electron/js2c/browser_init:2:85699)
at WebContents.emit (node:events:519:28)
```
And this terminal console  error that fires on mouse over clickable elements:

```
[25633:1114/105340.429490:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
```

I am on a Mac.

A few minutes later...

1)  Adding a switch statement to not use "setTitleBarOverlay" on Mac fixed the first error.

2) Updating all the packages fixed the second error

```
npx npm-check-updates -u && npm install
```

**Comment by codec-xyz** [comment]
Thanks for the issue. I don't have a mac to test the fix. I updated the npm packages and added a check before calling `setTitleBarOverlay` as you said. Feel free to close this issue if every is working.

**Comment by Acumen-Desktop** [comment]
I have both a Mac and Windows and soon a Linux for building/testing. I normally work solo, so I do not have much experience with the 'github' way of contributing to someone else's codebase. But this would be a good place to start. There are a lot of small issues converting from CommonJS to ESM, so you may see some attempts from me ;)
